from typing import TypedDict, Optional, Any
import re
from pydantic import BaseModel, Field, field_validator


# ─────────────────────────────────────────────────────────────────────────────
# 1. The Pydantic Model (Forces the LLM to output strict JSON)
#    Used by the Voice Agent (with_structured_output) and all booking nodes.
# ─────────────────────────────────────────────────────────────────────────────
class PatientData(BaseModel):
    name: Optional[str] = Field(default=None, max_length=100, description="The full name of the patient")
    age: Optional[int] = Field(default=None, ge=0, le=150, description="The age of the patient in years")
    phone: Optional[str] = Field(default=None, max_length=20, description="The 10-digit Indian mobile number")
    test_type: Optional[str] = Field(default=None, max_length=150, description="The specific medical test(s) requested, e.g., CBC, Lipid Profile")
    status: str = Field(default="booked", max_length=50, description="Current booking status: booked, sample_collected, delivered")
    payment_status: str = Field(default="pending", max_length=50, description="Payment status: pending or paid")
    report_link: Optional[str] = Field(default=None, max_length=500, description="URL to the uploaded PDF report")

    # ── Validators ────────────────────────────────────────────────────────────

    @field_validator("phone", mode="before")
    @classmethod
    def validate_phone(cls, v: Any) -> Optional[str]:
        """Validate Indian mobile number: must be 10 digits starting with 6-9."""
        if v is None:
            return v
        v = str(v)
        # Strip spaces, dashes, and leading +91 / 91
        cleaned = re.sub(r"[\s\-]", "", v)
        cleaned = re.sub(r"^(\+?91)", "", cleaned)
        if not re.match(r"^[6-9]\d{9}$", cleaned):
            raise ValueError(f"Invalid Indian mobile number: {v}")
        return cleaned

    @field_validator("name")
    @classmethod
    def validate_name(cls, v: Optional[str]) -> Optional[str]:
        """Sanitise name: strip whitespace, limit length, remove HTML tags."""
        if v is None:
            return v
        # Strip HTML tags
        v = re.sub(r"<[^>]+>", "", v)
        v = v.strip()
        if len(v) > 100:
            v = v[:100]
        if len(v) < 1:
            return None
        return v

    @field_validator("test_type")
    @classmethod
    def validate_test_type(cls, v: Optional[str]) -> Optional[str]:
        """Sanitise test_type: strip whitespace, limit length."""
        if v is None:
            return v
        v = re.sub(r"<[^>]+>", "", v)
        v = v.strip()
        if len(v) > 100:
            v = v[:100]
        return v if v else None

    @field_validator("age")
    @classmethod
    def validate_age(cls, v: Optional[int]) -> Optional[int]:
        """Age must be between 0 and 150."""
        if v is None:
            return v
        if v < 0 or v > 150:
            raise ValueError(f"Invalid age: {v}")
        return v

    @field_validator("status")
    @classmethod
    def validate_status(cls, v: str) -> str:
        allowed = {"booked", "sample_collected", "delivered"}
        if v not in allowed:
            raise ValueError(f"Invalid status '{v}'. Allowed: {allowed}")
        return v

    @field_validator("payment_status")
    @classmethod
    def validate_payment_status(cls, v: str) -> str:
        allowed = {"pending", "paid"}
        if v not in allowed:
            raise ValueError(f"Invalid payment_status '{v}'. Allowed: {allowed}")
        return v


# ─────────────────────────────────────────────────────────────────────────────
# 2. The LangGraph State (The memory passed between nodes)
#    Every node reads this dict, modifies it, and returns the updated dict.
# ─────────────────────────────────────────────────────────────────────────────
class OrchestratorState(TypedDict):
    # Routing Context
    event_type: str            # 'voice_call', 'whatsapp_walkin', 'whatsapp_collector', 'whatsapp_payment', 'pdf_upload'
    lab_id: str                # UUID of the tenant lab (TENANT ISOLATION KEY)
    patient_id: Optional[str]  # UUID of the patient (if already exists)

    # Conversation Buffers
    user_text: Optional[str]   # Raw text from STT or WhatsApp Webhook
    agent_speech: Optional[str]# Text generated by LLM to be sent to TTS

    # The Extracted Data Payload
    patient_data: PatientData

    # System Flags
    missing_fields: list[str]  # Tracks what the Voice Agent still needs to ask
    dispatch_success: bool     # Tracks if Meta API successfully sent the WhatsApp message

    # ── Collector / Payment / Report fields ──────────────────────────────────
    booking_id: Optional[str]         # UUID of the booking being updated
    sample_status: Optional[str]      # collected, in_transit, delivered, failed
    collector_phone: Optional[str]    # Collector's WhatsApp number

    # Payment
    payment_amount: Optional[float]   # Amount paid (in INR)
    payment_method: Optional[str]     # cash, upi, card, etc.

    # Report
    report_link: Optional[str]        # URL to the uploaded PDF report in Supabase Storage

# Alias so all existing node imports (from app.graph.state import AgentState) work
AgentState = OrchestratorState